layout_spectrum: 0.732796
typography_spectrum: 0.9183657
color:
  saturation: 0.861641
  lightness: 0.2075118
  brandStrength: 0.4952913
  rhythmicContrast: 0.8870986
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: KsK4459a2
